name: deploy

on:
  workflow_run:
      workflows: [test] # Triggered by the test workflow
      types: [completed] # The test workflow must complete
      branches: [main] # Only when main is updated

jobs:
  on-success:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only when test completed successfully 
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: backend
        run: npm install


      - name: zip up folder
        run: zip -r "musclmate_backend_deploy-${{github.sha}}.zip" backend
        
      - name: Congifure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2" 

      - name: Upload application file to AWS
        run: aws s3 cp musclmate_backend_deploy-${{github.sha}}.zip s3://terraform-state-muscleman-lordfarquaadthecreator

      - name: Create new application version
        run: |  
          aws elasticbeanstalk create-application-version \
          --application-name backend \
          --source-bundle S3Bucket="terraform-state-muscleman-lordfarquaadthecreator",S3Key="musclmate_backend_deploy-${{github.sha}}.zip " \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy application
        run: aws elasticbeanstalk update-environment --environment-name terraform-deploy-backend --version-label "ver-${{ github.sha }}"